### ISSUE TITLE
On Part 3

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/solving-a-lab-nitrous#2]
Not a big issue just thought you might want to correct it. After the Mr. Miyagi gif the list of 4 items was reset and the number was "1" instead of "4". Nothing else! 

Excited for the rest of the program!
-PJ

**Comment by aviflombaum** [comment]
Thanks @pajamaw - fixed f54dd0c4e9aa1ce20e2a4f0509e78176b3f4f31f
